<a href="https://colab.research.google.com/github/Shanmugaa2007/StudentGradePredictModel/blob/main/StudentGradePredictModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import pandas as pd

In [46]:
df = pd.read_csv('student_performance_dataset.csv')

In [10]:
df

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [47]:
df.count()

student_id                    1000
gender                        1000
study_time_hours              1000
attendance_percent            1000
sleep_hours                   1000
parental_education             898
internet_access               1000
extracurricular_activities    1000
part_time_job                 1000
previous_grade                1000
final_exam_score              1000
final_grade                   1000
dtype: int64

In [48]:
df.isna().sum()

student_id                      0
gender                          0
study_time_hours                0
attendance_percent              0
sleep_hours                     0
parental_education            102
internet_access                 0
extracurricular_activities      0
part_time_job                   0
previous_grade                  0
final_exam_score                0
final_grade                     0
dtype: int64

In [49]:
df = df.drop('parental_education',axis=1)

In [50]:
df

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Yes,No,No,45.4,70.4,C

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
lr = LabelEncoder()

In [62]:
x = df.drop('final_grade',axis=1)

In [55]:
df['gender'] = lr.fit_transform(df['gender'])

In [56]:
lr.classes_

array(['Female', 'Male'], dtype=object)

In [57]:
df['internet_access'] = lr.fit_transform(df['internet_access'])

In [58]:
df['extracurricular_activities'] = lr.fit_transform(df['extracurricular_activities'])

In [59]:
df['part_time_job'] = lr.fit_transform(df['part_time_job'])

In [60]:
y = df['final_grade']

In [61]:
x

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score
0,1,Male,4.0,98.0,6.5,Yes,Yes,No,76.9,100.0
1,2,Female,6.3,100.0,5.7,Yes,Yes,Yes,75.5,100.0
2,3,Male,4.9,85.3,7.9,Yes,No,Yes,88.5,97.3
3,4,Male,2.6,77.5,8.0,Yes,Yes,No,85.1,83.8
4,5,Male,2.2,89.6,4.6,Yes,No,Yes,61.8,68.3
...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Yes,Yes,No,60.5,70.7
996,997,Male,6.7,88.4,7.1,No,Yes,No,82.2,99.5
997,998,Female,2.6,84.5,8.0,Yes,Yes,Yes,65.2,79.2
998,999,Female,4.6,85.3,8.1,No,No,Yes,52.2,82.2
999,1000,Male,3.9,77.4,6.1,Yes,No,No,45.4,70.4

In [37]:
y

0      A
1      A
2      A
3      B
4      D
      ..
995    C
996    A
997    C
998    B
999    C
Name: final_grade, Length: 1000, dtype: object

In [63]:
from sklearn.model_selection import train_test_split

In [64]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.2)

In [72]:
x_test

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score
169,170,0,2.9,88.7,7.4,0,1,1,60.1,78.1
101,102,0,1.9,67.4,6.7,1,1,1,75.5,66.3
64,65,1,3.4,88.1,5.7,1,0,1,47.9,80.8
388,389,1,4.4,77.6,6.2,1,0,1,91.0,86.7
364,365,1,2.1,58.0,8.9,1,1,0,61.5,57.4
...,...,...,...,...,...,...,...,...,...,...
675,676,1,0.5,83.6,6.4,0,1,1,71.9,61.3
482,483,1,4.5,74.1,7.4,1,0,1,80.5,86.6
528,529,0,3.4,67.0,7.6,0,0,0,93.4,84.3
746,747,1,5.9,91.7,4.7,1,1,1,57.3,100.0
794,795,1,3.8,83.1,8.0,1,0,0,75.7,89.5

In [73]:
y_test

169    C
101    D
64     B
388    B
364    F
      ..
675    D
482    B
528    B
746    A
794    B
Name: final_grade, Length: 800, dtype: object

In [65]:
x_train

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score
542,543,1,5.8,96.0,8.7,1,1,1,53.5,88.8
0,1,1,4.0,98.0,6.5,1,1,0,76.9,100.0
839,840,1,3.3,98.2,5.6,1,0,1,63.9,82.9
82,83,1,2.7,73.0,7.6,1,0,1,55.3,64.1
265,266,0,5.2,88.3,8.6,1,0,0,86.8,100.0
...,...,...,...,...,...,...,...,...,...,...
993,994,0,6.2,87.6,5.9,1,0,0,75.4,92.7
23,24,0,4.3,82.5,5.4,0,1,0,61.0,71.2
35,36,1,6.1,95.7,8.2,1,1,1,78.5,92.9
803,804,1,2.0,90.9,9.0,1,1,0,86.7,94.6
77,78,0,3.8,76.5,5.3,1,1,0,72.3,79.3

In [66]:
from sklearn.linear_model import LogisticRegression

In [91]:
le = LogisticRegression(max_iter=500000)

In [92]:
le.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF F,G EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=500000)

In [93]:
y_predict = le.predict(x_test)

In [94]:
y_predict

array(['C', 'D', 'B', 'B', 'D', 'C', 'A', 'B', 'C', 'D', 'B', 'B', 'D',
       'B', 'D', 'C', 'C', 'C', 'A', 'C', 'A', 'C', 'C', 'B', 'A', 'B',
       'C', 'D', 'B', 'D', 'C', 'B', 'C', 'A', 'B', 'B', 'D', 'B', 'C',
       'B', 'C', 'B', 'A', 'C', 'C', 'B', 'A', 'B', 'A', 'A', 'A', 'B',
       'B', 'C', 'B', 'A', 'B', 'C', 'A', 'C', 'C', 'A', 'B', 'D', 'B',
       'C', 'B', 'D', 'C', 'B', 'B', 'B', 'B', 'A', 'B', 'B', 'C', 'B',
       'C', 'B', 'B', 'C', 'A', 'D', 'D', 'A', 'A', 'B', 'D', 'B', 'A',
       'C', 'D', 'A', 'B', 'C', 'C', 'B', 'D', 'C', 'C', 'A', 'C', 'A',
       'C', 'B', 'A', 'B', 'D', 'A', 'A', 'A', 'B', 'B', 'D', 'C', 'C',
       'A', 'B', 'A', 'C', 'A', 'B', 'B', 'A', 'A', 'A', 'B', 'A', 'A',
       'C', 'C', 'B', 'A', 'C', 'B', 'A', 'B', 'B', 'D', 'B', 'B', 'B',
       'D', 'A', 'D', 'B', 'B', 'B', 'D', 'B', 'B', 'C', 'A', 'B', 'A',
       'A', 'A', 'C', 'B', 'B', 'A', 'D', 'B', 'C', 'C', 'A', 'C', 'C',
       'D', 'C', 'B', 'B', 'A', 'A', 'B', 'B', 'D', 'B', 'C', 'B', 'A',
       'C', 'C', 'A', 'A', 'A', 'B', 'C', 'B', 'A', 'C', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'B', 'A', 'B', 'D',
       'B', 'A', 'B', 'B', 'C', 'A', 'C', 'B', 'A', 'D', 'B', 'C', 'B',
       'A', 'B', 'A', 'B', 'A', 'B', 'C', 'B', 'A', 'B', 'D', 'A', 'A',
       'C', 'A', 'B', 'B', 'B', 'A', 'B', 'B', 'A', 'A', 'C', 'A', 'A',
       'B', 'C', 'A', 'B', 'C', 'B', 'A', 'A', 'B', 'A', 'B', 'B', 'C',
       'A', 'C', 'C', 'A', 'C', 'D', 'F', 'B', 'B', 'B', 'B', 'C', 'B',
       'A', 'C', 'A', 'B', 'B', 'A', 'C', 'B', 'B', 'C', 'B', 'A', 'B',
       'C', 'B', 'C', 'A', 'B', 'B', 'A', 'C', 'F', 'B', 'B', 'B', 'C',
       'A', 'D', 'A', 'A', 'C', 'A', 'C', 'A', 'B', 'C', 'A', 'A', 'B',
       'A', 'B', 'C', 'A', 'B', 'B', 'D', 'B', 'C', 'B', 'C', 'C', 'A',
       'D', 'B', 'C', 'A', 'B', 'B', 'A', 'C', 'A', 'B', 'A', 'B', 'A',
       'B', 'B', 'A', 'A', 'B', 'B', 'A', 'B', 'B', 'A', 'A', 'A', 'A',
       'B', 'A', 'A', 'B', 'A', 'C', 'B', 'F', 'A', 'C', 'C', 'A', 'B',
       'B', 'B', 'C', 'A', 'C', 'A', 'A', 'B', 'A', 'C', 'B', 'B', 'B',
       'A', 'A', 'B', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'C',
       'A', 'C', 'C', 'C', 'A', 'B', 'A', 'B', 'B', 'A', 'C', 'B', 'B',
       'A', 'B', 'A', 'A', 'B', 'B', 'A', 'B', 'D', 'C', 'A', 'C', 'C',
       'B', 'C', 'A', 'C', 'C', 'B', 'B', 'B', 'A', 'B', 'D', 'D', 'C',
       'C', 'B', 'A', 'A', 'C', 'B', 'C', 'A', 'D', 'B', 'C', 'B', 'B',
       'A', 'A', 'B', 'B', 'C', 'B', 'B', 'C', 'A', 'A', 'C', 'C', 'C',
       'A', 'A', 'A', 'C', 'C', 'C', 'B', 'B', 'C', 'C', 'B', 'A', 'B',
       'B', 'D', 'C', 'B', 'A', 'C', 'A', 'A', 'C', 'A', 'A', 'B', 'A',
       'B', 'A', 'A', 'A', 'B', 'C', 'B', 'C', 'A', 'C', 'A', 'F', 'A',
       'C', 'B', 'B', 'A', 'D', 'B', 'A', 'B', 'C', 'B', 'A', 'A', 'C',
       'B', 'C', 'C', 'A', 'C', 'C', 'B', 'C', 'B', 'C', 'D', 'B', 'B',
       'A', 'C', 'F', 'A', 'B', 'B', 'B', 'C', 'B', 'B', 'B', 'B', 'C',
       'A', 'D', 'A', 'B', 'B', 'B', 'A', 'B', 'C', 'D', 'B', 'A', 'A',
       'B', 'B', 'C', 'A', 'A', 'B', 'C', 'B', 'C', 'B', 'C', 'B', 'A',
       'C', 'B', 'C', 'C', 'C', 'B', 'A', 'B', 'C', 'A', 'B', 'A', 'D',
       'B', 'C', 'C', 'B', 'B', 'C', 'B', 'C', 'B', 'D', 'A', 'A', 'A',
       'D', 'C', 'B', 'A', 'D', 'B', 'C', 'B', 'C', 'A', 'D', 'C', 'C',
       'B', 'C', 'A', 'C', 'B', 'A', 'C', 'A', 'C', 'A', 'A', 'F', 'C',
       'B', 'B', 'D', 'B', 'B', 'C', 'A', 'F', 'B', 'B', 'A', 'C', 'B',
       'B', 'B', 'A', 'B', 'B', 'C', 'A', 'A', 'A', 'B', 'C', 'C', 'A',
       'C', 'B', 'B', 'C', 'B', 'B', 'B', 'A', 'A', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'C', 'F', 'A', 'B', 'A', 'B', 'C', 'A', 'C',
       'B', 'A', 'A', 'A', 'C', 'D', 'C', 'D', 'F', 'B', 'B', 'A', 'B',
       'F', 'B', 'B', 'C', 'C', 'B', 'B', 'A', 'A', 'A', 'B', 'B', 'A',
       'A', 'A', 'C', 'A', 'A', 'A', 'C', 'B', 'A', 'C', 'A', 'B', 'A',
       'C', 'B', 'A', 'C', 'C', 'B', 'A', 'B', 'A', 'B', 'A', 'C', 'C',
       'C', 'A', 'C', 'B', 'B', 'B', 'A', 'B', 'B', 'A', 'C', 'B', 'B',
       'B', 'B', 'B', 'C', 'B', 'B', 'B', 'B', 'C', 'B', 'B', 'B', 'D',
       'F', 'B', 'A', 'D', 'B', 'B', 'A', 'A', 'A', 'A', 'B', 'C', 'B',
       'B', 'B', 'B', 'A', 'B', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'A',
       'C', 'C', 'A', 'C', 'C', 'A', 'C', 'B', 'B', 'B', 'C', 'B', 'D',
       'D', 'B', 'B', 'B', 'B', 'B', 'C', 'B', 'C', 'C', 'B', 'B', 'A',
       'B', 'B', 'D', 'B', 'B', 'A', 'A'], dtype=object)

In [74]:
from sklearn.metrics import classification_report

In [95]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           A       0.95      0.94      0.94       230
           B       0.81      0.94      0.87       275
           C       0.87      0.78      0.82       213
           D       0.87      0.62      0.72        74
           F       0.18      0.25      0.21         8

    accuracy                           0.86       800
   macro avg       0.74      0.71      0.72       800
weighted avg       0.87      0.86      0.86       800